CREATE DATABASE library;
CREATE DATABASE library_test;
CREATE USER admin WITH ENCRYPTED PASSWORD 'admin';
GRANT ALL PRIVILEGES ON DATABASE library TO admin;
GRANT ALL PRIVILEGES ON DATABASE library_test TO admin;
ALTER USER admin CREATEDB;
ALTER USER admin WITH SUPERUSER;
